### ISSUE TITLE
expand_targets does not deal with more than two dots

### ISSUE THREAD

**Issue by fj40crawler** [opennode/salt-safeguard#1]
If a fqdn is used then expand_targets checks for exactly 2 dots. Ideally the code would check for -ge 2 so that 2 or more dots would be considered a fqdn. This logic is in the function twice.

As a side note the 'does not confirm' message probably wants to be 'does not conform'

Great idea overall so thanks for that!

**Comment by mainframe** [comment]
@fj40crawler could you submit a patch / merge request?

**Comment by mainframe** [comment]
Merged https://github.com/opennode/salt-safeguard/commit/1db0fb4797b18eff6c1d6abee50428f01443c730
